### ISSUE TITLE
Inconsistent default vs props-passed className precedence

### ISSUE THREAD

**Issue by jbkolze** [USACE/groundwork#31]
Within groundwork there is some inconsistency with application of default classNames vs. props-passed classNames.  Ideally, props-passed classNames would always take precedence, but this is not always the case.  Example: If you pass a custom width to a Card component it still maintains its default full-width.

This can be bypassed by using a "!" operator in front of the class, e.g. className="!gw-w-48".  However, if you do this then the user **also** has to use a "!" operator in order to adjust the class you modified, e.g. className-"!w-36".  So, you're somewhat passing the buck to the user end, which isn't ideal.

May be worth investigating other solutions, e.g. [tailwind-merge](https://www.npmjs.com/package/tailwind-merge)

**Comment by adamscarberry** [comment]
However this is implemented, I think we need something like the following for the config:

```javascript
import { extendTailwindMerge } from 'tailwind-merge';

export const twMerge = extendTailwindMerge({
  prefix: 'gw-',
});

Although I don't know what happens when we pass in normal tailwind classnames from the consuming app.
```

**Comment by adamscarberry** [comment]
@jbkolze is this still an issue?

**Comment by willbreitkreutz** [comment]
@jbkolze @adamscarberry  I'm playing with tailwind-merge now, It looks like it works well as long as the classes you pass in are prefixed matching the config, the issue is when we build, only the used classes are bundled so we still run into the missing classes issue, even if we tell consumers to use the `gw-` prefix to override.  I'm going to dig a little deeper and see if I can come up with a way to let you pass in a normal tailwind class, and still have it override the prefixed one.
