### ISSUE TITLE
Feature Request: Timeseries Data Table/Plot Components

### ISSUE THREAD

**Issue by msweier** [USACE/groundwork#86]
Something some folks in the field and myself would find useful to help get started with our websites are some simple components that return or plot timeseries data. Some examples:

- [ ] Component that will accept a TSID  and return public name and latest time and latest value as a table row or multiple TSIDs and return the table of latest values (similar to https://www.mvp-wc.usace.army.mil/gages/web-gages-MississippiHeadwaters.shtml but with just one parameter)
- [ ] Component that will accept a TSID and lookback time and create a table of times and values (similar to 
![image](https://github.com/user-attachments/assets/1d608f20-d57d-42b0-942f-e7f20dfe8ae8)

- [ ] Component that will accept a TSID and lookback time and create a plot (similar to https://www.mvp-wc.usace.army.mil/graphs/MissHW_Gull.Elev.Inst.1Hour.0.rev-NGVD29.png)

These hopefully simple components could be used as a springboard to making more complex custom components.

**Comment by adamscarberry** [comment]
@msweier Is this what you're looking for?  https://github.com/USACE-WaterManagement/groundwork-water

**Comment by msweier** [comment]
> @msweier Is this what you're looking for? https://github.com/USACE-WaterManagement/groundwork-water

Probably?

**Comment by krowvin** [comment]
@msweier 
You and I spoke some last week about this. 

Adam is correct in that the `groundwork-water` is where the components you are thinking of will live. 
@jbkolze and I have talked on this some and will kick it into gear. I will also look into deploying that package this week and reach out for you to try it otu. 

But yes - please post WM specific components requests on 
https://github.com/USACE-WaterManagement/groundwork-water

I tried to migrate this over but I think because it's in another ORG it wouldn't let me. 

@adamscarberry @willbreitkreutz 
Can we see about hiding the WM dropdown from this repo since we are going this route?

**Comment by adamscarberry** [comment]
@krowvin Can you or @jbkolze start moving the WM components out of groundwork and into the wm repo?
